name: renate_od_conda
channels:
  - defaults
dependencies:
  - h5py = 2.6.0
  - ipykernel = 4.5.2
  - lxml = 3.7.2
  - matplotlib = 2.0.0
  - numpy = 1.11.3
  - pandas = 0.19.2
  - python = 3.6.0
  - scipy = 1.0.0
